### ISSUE TITLE
Linreg_epi2t1_afni

### ISSUE THREAD

**Issue by naailk** [aigoyal/EPItome-xl#10]
When trying to use the linreg_epi2t1_afni module the following error is produced:

Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epitome", line 764, in <module>
    run_epitome()
  File "/srv/CODE/epitome/bin/epitome", line 665, in run_epitome
    line, output = eval(command)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'linreg_epi2t1_afni'

**Comment by josephdviviano** [comment]
Looks like I missed this one :) just had to add a command.py file and a doc.md file.

@aigoyal , I've fixed this and pushed the changes to the master branch of my repo. There are some other back end changes that should not affect the running of epitome, but let me know if you run into trouble.

**Comment by aigoyal** [comment]
Updated the pipeline with the latest from you Joseph. Thanks.

**Comment by josephdviviano** [comment]
No problem. I like this workflow.
