### ISSUE TITLE
EPI masking crash

### ISSUE THREAD

**Issue by k8ywalsh** [aigoyal/EPItome-xl#12]
Right after choosing option 3 for EPI masking, epitome crashed. The following is the message I received. I have tried again just to be sure there is an actual error, and the same thing happened.

EPI masking: acquisition dependent
    1: loose
    2: loosest
    3: normal
    4: tight
option #: 3

Please select the next pipeline module:

Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epitome", line 758, in <module>
    main()
  File "/srv/CODE/epitome/bin/epitome", line 649, in main
    module, used = get_modules(moduletype='pre', used=used)
  File "/srv/CODE/epitome/bin/epitome", line 42, in get_modules
    module_types = os.listdir(os.path.join(DIR_PIPE, 'epitome/modules'))
OSError: [Errno 20] Not a directory: '/srv/CODE/epitome/bin/epitome/modules'

**Comment by josephdviviano** [comment]
Yikes, sorry about this, there was a typo in config.py.

@aigoyal , I've pushed the fix to master.

**Comment by aigoyal** [comment]
Thanks Joseph. I've updated the pipeline at ours.
