### ISSUE TITLE
epitome run not working

### ISSUE THREAD

**Issue by naailk** [aigoyal/EPItome-xl#14]
When entering the epitome run command I receive this error:

ERROR: Manditory EPITOME_DATA variable is not set.

**Comment by josephdviviano** [comment]
Yes the datavdirectory is no longer set in config.py, it is now.an environment variable. Aman could put this I the global bashrc or uou could put it.in your local one. Nothing needs to be changed in the config.py file any longer as users found that confusing. See the.documentation for more.

**Comment by aigoyal** [comment]
The EPITOME_DATA environment variable is already set in the global bashrc. 

@naailk, you may need to log out and then log back in.

**Comment by naailk** [comment]
Great, it is working now thanks.
