### ISSUE TITLE
Linreg_epi2t1_afni

### ISSUE THREAD

**Issue by naailk** [aigoyal/EPItome-xl#17]
When selecting this module, it does not appear in the master list. Instead linreg_ti2mni_afni does.

**Comment by josephdviviano** [comment]
oops, simple typo in the commands/linreg_epi2t1_afni.py file. Fixed in latest push to `master`.

**Comment by aigoyal** [comment]
@naailk : epitome on harford is now up-to-date with Joseph's.
@josephdviviano : that feature which allows ability to choose a replicant up front ... really useful!
