### ISSUE TITLE
Using 1D files instead of .PHYS

### ISSUE THREAD

**Issue by naailk** [aigoyal/EPItome-xl#19]
This is less of an issue and more of a question. I have physiological data for heart rate and respiration in 1D files not .PHYS. Will this be compatible with the pipeline and if not what should I do to convert it?

**Comment by josephdviviano** [comment]
Hi Nikhil, where did you get those 1D files? You could just rename them.

**Comment by naailk** [comment]
These files are from NIH. Neither Aman or I were sure renaming would work hence the post. Do you know of the top of your head how the data should be arranged in these files?

**Comment by josephdviviano** [comment]
No.

**Comment by naailk** [comment]
I figured this out. Data needed to be in a single column and renamed to the proper format. I am closing this issue. Thanks for the help.
