### ISSUE TITLE
'epitome run' crashes

### ISSUE THREAD

**Issue by aigoyal** [aigoyal/EPItome-xl#4]
Hi Joseph,

So, git pulling the updated epitome to the server at ours did not help. That error still remains:

    epitome run
******************************************************************
             Running epitome. Select experiment.
******************************************************************
Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epitome", line 821, in <module>
    run_epitome()
  File "/srv/CODE/epitome/bin/epitome", line 548, in run_epitome
    dir_matlab = epi.config.find_matlab()
  File "/srv/CODE/epitome/epitome/config.py", line 49, in find_matlab
    dir_matlab = subprocess.check_output('which matlab', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'which matlab' returned non-zero exit status 1    

Thoughts?!

**Comment by josephdviviano** [comment]
What does `epitome check` say?

is matlab on your path?

**Comment by aigoyal** [comment]
This is what 'epitome check' returns:

    epitome check

*********************************************
config.py appears to be properly configured!

     data directory: /srv/MRI/WORKING
     pipeline directory: /srv/CODE/epitome
     AFNI directory: /usr/local/abin
     McRetroTS found: /opt/mcretro
     MATLAB found: /opt/MATLAB/MATLAB_Compiler_Runtime/v715
*********************************************

**Comment by josephdviviano** [comment]
Hi Aman,

I'm not sure if you got the updates. Can you pull again from the kimel branch?

**Comment by aigoyal** [comment]
Okay Joseph, so I've pulled epitome again. The one with the `dir_matlab = '/'.join(dir_matlab.split('/')[-2])` in the config.py .

Now, `epitome run` and `epitome check` both are crashing with the same error.

**Comment by josephdviviano** [comment]
What does 'which matlab' give on the command line?

**Comment by josephdviviano** [comment]
Hi aman.

matlab wasn't on the system path. I added it in bash.bashrc.local

also because you pulled some major changes I made last night, you inherited some highly untested code. merge the most recent changes and try again.

**Comment by aigoyal** [comment]
I've pulled the latest epitome to ours. `epitome check` and `epitome run` don't quit as before. 

Thanks Joseph.

**Comment by josephdviviano** [comment]
It's not a problem, but do you realize that this is because you didn't have matlab on your path? This is important.

**Comment by aigoyal** [comment]
Yes, got it.

**Comment by josephdviviano** [comment]
Let's close this issue.
