### ISSUE TITLE
pull new changes to epitome

### ISSUE THREAD

**Issue by josephdviviano** [aigoyal/EPItome-xl#7]
Hi Aman,

I've made some more changes to epitome that you should pull. Otherwise you will have problems down the road.

Thanks!

**Comment by josephdviviano** [comment]
to prevent this happening in the future I've changed the organization of my epitome branch:

+ master -- this is code that I at least **think** works. If I decide to hack away, it won't be here.
+ dev -- I'll be actively developing this branch and pushing those changes over to master periodically. If you notice an update to master, you might want it, but don't pull from dev.

Let me know if this is confusing.

**Comment by aigoyal** [comment]
Just so I understand this:

The "master" is the release version of the pipeline. You will be updating it periodically. And I should keep the pipeline at ours current with this.

The "dev" will be the "beta" version ... a Works-In-Progress version. I should not pull from this when updating the pipeline at ours.

Is that correct?

**Comment by josephdviviano** [comment]
correct!
